// frontend/src/components/pipeline/KanbanBoard.tsx
import { useState, useMemo } from 'react';
import type { PipelineProject, PipelineStage } from '@/types/pipeline.types';
import { ProjectCard } from './ProjectCard';

interface Props {
  projects: PipelineProject[];
  stages: PipelineStage[];
  onMoveProject: (projectId: string, newStageId: string) => Promise<void>;
}

export function KanbanBoard({ projects, stages, onMoveProject }: Props) {
  const [draggedProject, setDraggedProject] = useState<PipelineProject | null>(null);
  const [dragOverStageId, setDragOverStageId] = useState<string | null>(null);

  const stagesWithProjects = useMemo(() => {
    return stages.map(stage => {
      const stageProjects = projects.filter(p => p.stageId === stage.id);
      return {
        ...stage,
        projects: stageProjects,
        totalValue: stageProjects.reduce((sum, p) => sum + p.value, 0),
        projectCount: stageProjects.length,
      };
    });
  }, [stages, projects]);

  const handleDragStart = (project: PipelineProject) => {
    setDraggedProject(project);
  };

  const handleDragOver = (event: React.DragEvent, stageId: string) => {
    event.preventDefault();
    setDragOverStageId(stageId);
  };

  const handleDragLeave = () => {
    setDragOverStageId(null);
  };

  const handleDrop = async (event: React.DragEvent, toStageId: string) => {
    event.preventDefault();
    setDragOverStageId(null);

    if (!draggedProject || draggedProject.stageId === toStageId) {
      setDraggedProject(null);
      return;
    }

    await onMoveProject(draggedProject.id, toStageId);
    setDraggedProject(null);
  };

  const handleDragEnd = () => {
    setDraggedProject(null);
    setDragOverStageId(null);
  };

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      notation: 'compact',
      maximumFractionDigits: 1,
    }).format(value);
  };

  return (
    <div className="flex gap-4 overflow-x-auto pb-4 h-[calc(100vh-300px)]">
      {stagesWithProjects.map(stage => (
        <div
          key={stage.id}
          className={`flex-shrink-0 w-80 bg-slate-50 rounded-lg transition-all ${
            dragOverStageId === stage.id ? 'ring-2 ring-blue-500 bg-blue-50' : ''
          }`}
          onDragOver={(e) => handleDragOver(e, stage.id)}
          onDragLeave={handleDragLeave}
          onDrop={(e) => handleDrop(e, stage.id)}
        >
          {/* Column Header */}
          <div className="p-4 border-b border-slate-200 bg-white rounded-t-lg">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <div
                  className="w-3 h-3 rounded-full"
                  style={{ backgroundColor: stage.color }}
                />
                <h3 className="font-semibold text-slate-900">{stage.name}</h3>
              </div>
              <span className="px-2 py-1 text-xs font-medium bg-slate-100 text-slate-700 rounded-full">
                {stage.projectCount}
              </span>
            </div>
            <div className="text-sm text-slate-600">
              {formatCurrency(stage.totalValue)}
            </div>
          </div>

          {/* Column Content */}
          <div className="p-3 space-y-3 overflow-y-auto max-h-[calc(100vh-400px)]">
            {stage.projects.length === 0 ? (
              <div className="text-center py-8 text-slate-400">
                <p className="text-sm">No projects</p>
              </div>
            ) : (
              stage.projects.map(project => (
                <ProjectCard
                  key={project.id}
                  project={project}
                  stageColor={stage.color}
                  onDragStart={handleDragStart}
                  onDragEnd={handleDragEnd}
                />
              ))
            )}
          </div>
        </div>
      ))}
    </div>
  );
}

// oc-pipeline-main/frontend/src/components/pipeline/KanbanBoard.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { usePipelineStore } from '@/stores/pipeline';
import { getStagesByType } from '@/config/pipeline-stages';
import type { PipelineType, PipelineProject } from '@/types/pipeline.types';
import KanbanColumn from './KanbanColumn.vue';
import ProjectCard from './ProjectCard.vue';

interface Props {
  type: PipelineType;
}

const props = defineProps<Props>();

const pipelineStore = usePipelineStore();
const draggedProject = ref<PipelineProject | null>(null);
const dragOverStageId = ref<string | null>(null);

const stages = computed(() => getStagesByType(props.type));

const stagesWithProjects = computed(() => {
  return stages.value.map(stage => ({
    ...stage,
    projects: pipelineStore.projectsByStage[stage.id] || [],
    totalValue: (pipelineStore.projectsByStage[stage.id] || [])
      .reduce((sum, p) => sum + p.value, 0),
    projectCount: (pipelineStore.projectsByStage[stage.id] || []).length,
  }));
});

const handleDragStart = (project: PipelineProject) => {
  draggedProject.value = project;
};

const handleDragOver = (event: DragEvent, stageId: string) => {
  event.preventDefault();
  dragOverStageId.value = stageId;
};

const handleDragLeave = () => {
  dragOverStageId.value = null;
};

const handleDrop = async (event: DragEvent, toStageId: string) => {
  event.preventDefault();
  dragOverStageId.value = null;

  if (!draggedProject.value) return;

  const success = await pipelineStore.moveProject(
    draggedProject.value.id,
    toStageId
  );

  draggedProject.value = null;
};

const handleDragEnd = () => {
  draggedProject.value = null;
  dragOverStageId.value = null;
};

onMounted(() => {
  pipelineStore.fetchProjects(props.type);
});
</script>

<template>
  <div class="kanban-board">
    <div v-if="pipelineStore.isLoading" class="loading-overlay">
      <div class="spinner"></div>
      <p>Loading pipeline...</p>
    </div>

    <div v-else class="kanban-columns">
      <KanbanColumn
        v-for="stage in stagesWithProjects"
        :key="stage.id"
        :stage="stage"
        :is-drag-over="dragOverStageId === stage.id"
        @dragover="handleDragOver($event, stage.id)"
        @dragleave="handleDragLeave"
        @drop="handleDrop($event, stage.id)"
      >
        <ProjectCard
          v-for="project in stage.projects"
          :key="project.id"
          :project="project"
          :stage-color="stage.color"
          draggable="true"
          @dragstart="handleDragStart(project)"
          @dragend="handleDragEnd"
        />
      </KanbanColumn>
    </div>
  </div>
</template>

<style scoped>
.kanban-board {
  position: relative;
  height: calc(100vh - 200px);
  overflow-x: auto;
  overflow-y: hidden;
  padding: 16px;
}

.kanban-columns {
  display: flex;
  gap: 12px;
  min-width: min-content;
  height: 100%;
}

.loading-overlay {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 400px;
  gap: 12px;
}

.spinner {
  width: 48px;
  height: 48px;
  border: 4px solid #E5E7EB;
  border-top-color: #3B82F6;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>
